### ISSUE TITLE
VHDL Conversion

### ISSUE THREAD

**Issue by darsor** [SystemRDL/PeakRDL-regblock-vhdl#6]
# Tracking issue for VHDL conversion

### Goals for VHDL conversion:
* Keep the structure and conventions of the code as much as possible, to allow merging back into upstream in the future if it makes sense.
* Support up to VHDL-2008 (no 2019 for now)

See #3 for an ongoing list of changes necessary to support VHDL semantics.

## Module Sections:
- [x] Hardware Interface (HWIF) (#1)
- [x] CPU Interface (CPUIF)
  - [x] AXI4-Lite
  - [x] APB3
  - [x] APB4
  - [x] Avalon (#13)
  - [x] Passthrough (#9)
- [x] Address Decode (#4)
- [x] Field Logic (#5)
- [x] Readback (#2)
- [x] Read buffering (#10)
- [x] Write buffering (#12)

### Goals for unit tests:
* Keep systemverilog tests as-is
  * Lots of effort to convert tests to VHDL, with potential bugs introduced
  * Helps keep this repo in sync with upstream

 - [x] Example RDL passes lint checks by VHDL-LS
 - [x] All test RDL passes lint checks by VHDL-LS (#8)
 - [x] VHDL -> SV adapter for unit tests (#11)
 - [x] Unit tests pass (#14)
 - [x] Synthesis tests pass (#18)

## Documentation:

- [x] Update readthedocs.io (#19)
